# Generated by Django 2.1.7 on 2019-04-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nuggets_api', '0002_auto_20190310_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuggetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_owner', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nugget_user',
            name='nugget',
        ),
        migrations.RemoveField(
            model_name='nugget_user',
            name='user',
        ),
        migrations.AddField(
            model_name='nugget',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Nugget_User',
        ),
        migrations.AddField(
            model_name='nuggetuser',
            name='nugget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuggets_api.Nugget'),
        ),
        migrations.AddField(
            model_name='nuggetuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
